version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "9090:9090"

  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - server